### ISSUE TITLE
Backport patches to wepoll-sys

### ISSUE THREAD

**Issue by YorickPeterse** [stjepang/wepoll-sys-stjepang#2]
In https://gitlab.com/yorickpeterse/wepoll-binding/-/issues/1 we chatted a bit about the patch you applied, and if that should belong in the upstream wepoll-sys crate. At the time I suggested trying to include this in wepoll itself. 

Based on the discussion in https://github.com/piscisaureus/wepoll/pull/20 and the surrounding issues, I suspect it will take quite some time for wepoll itself to support this. Since having two wepoll-sys crates is confusing, I'm fine with including the patches in wepoll-sys itself;  provided the changes are added in a `.patch` file, that way we can re-apply them easily if ever needed.

@stjepang what are your thoughts on this? I'd also be happy to add you as a co-maintainer/owner of the repositories/crates. That way if I get hit by a bus, forking the crates won't be necessary.

**Comment by stjepang** [comment]
Sounds like a good idea, agree with everything :) I'll make a PR with a `.patch` file later this week, but you can also do it sooner if you wish.

**Comment by stjepang** [comment]
Done.
